#!/bin/bash

DEST_SRV=megaton.klub.com.pl
DEST_DIR=/var/www/hevelius

if [ "$1" == "--help" ]; then
    echo "Hevelius deployment script"
    echo
    echo "Supported parameters:"
    echo "--help - displays this help"
    echo "--local - deploys locally"
    exit 1
fi

echo "STEP 1: building"
ng build

if [ $? -ne 0 ]; then
   echo "Building failed."
   exit 1
fi

if [ $# -ge 1 ] && [ $1 == "--local" ]; then
    DEST_HOST=
    if [ "`uname`" == "Darwin" ]; then
        DEST_DIR=~/public_html
    else
        DEST_DIR=/var/www/html
    fi
    echo "Deploying front-end locally (DEST_DIR=$DEST_DIR)"
    cd dist/hevelius
    cp -rv * $DEST_DIR
    echo "Deploying back-end locally (DEST_DIR=$DEST_DIR)"
    cd ../..
    cp -rv api $DEST_DIR
else
    DEST_HOST=megaton.klub.com.pl
    DEST_DIR=/var/www/hevelius
    echo "Deploying front-end remotely (DEST_HOST=$DEST_HOST, DEST_DIR=$DEST_DIR)"
    cd dist/hevelius
    scp -r * $DEST_HOST:$DEST_DIR
    echo "Deploying back-end remotely (DEST_HOST=$DEST_HOST, DEST_DIR=$DEST_DIR)"
    cd ../..
    scp -r api $DEST_HOST:$DEST_DIR
fi
